name: Publish Artifacts
on: workflow_dispatch
jobs:
    build:
        name: Build
        # TODO mac once we get it working
        # runs-on: macos-latest
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

            # - name: Setup Xcode
            #   uses: maxim-lobanov/setup-xcode@v1
            #   with:
            #       xcode-version: latest-stable

            - name: Publish To Maven Central
              env:
                  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
                  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
                  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
                  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
                  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
              run: |
                  chmod 777 ./gradlew
                  ./gradlew capitalizeLib:publishToMavenCentral --no-configuration-cache
